import { useState, useEffect } from 'react';
import io from 'socket.io-client';
import webSocket from 'socket.io-client';
import { SimpleSequentialChain, SequentialChain, LLMChain, RetrievalQAChain } from "langchain/chains";
import { OpenAI } from "langchain/llms/openai";
import { PromptTemplate } from "langchain/prompts";
import { OpenAIEmbeddings } from "langchain/embeddings/openai";
import { HNSWLib } from "langchain/vectorstores/hnswlib";
import { RecursiveCharacterTextSplitter } from "langchain/text_splitter";

const socket = io('192.168.1.183:4000');

const Fp = () => {  //Set name => set input(value) to be currenTitle, to the openai, and to the server if is certain value => set ai message and value to chat history(previousChats) => set currentChat from previousChats => display accroding to message owners
  
  const [value, setValue] = useState("");
  const [userInput, setUserInput] = useState(null);
  const [message, setMessage] = useState(null);
  const [messageSocket, setMessageSocket] = useState(null);
  const [previousChats, setPreviousChats] = useState([]);
  const [history, setHistory] = useState([]);
  const [currentTitle, setCurrentTitle] = useState(null);
  const [userName, setUserName] = useState(null);
  const [otheruserName, setOtheruserName] = useState(null);
  const [initialized, setInitialized] = useState(null);
  const [aiChain, setAiChain] = useState(null);
  const API_KEY = "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";
//==========================================================================================
  const firstAImessage = async () =>{
    const llm = new OpenAI({ openAIApiKey:API_KEY, temperature: 0.9 });
    const template = `The following is the chat history between two friendly humans, A and B. You are going to mimic human B and create a response for him/her.
    
    Chat History: {history}
    Human A: {input}
    Human B:`;
    const promptTemplate = new PromptTemplate({
      inputVariables: ["input", "history" ],
      template,
    });
    const chatChain = new LLMChain({
      llm,
      prompt: promptTemplate,
      outputKey: "chat"
    });
    
    // This is an LLMChain to write a review of a play given a synopsis.
    const checkLLM = new OpenAI({ openAIApiKey:API_KEY, temperature: 0 });
    const checkTemplate = `The following is the chat history between two friendly humans, A and B. An AI generated a message for human B to respond to human A, you are going to check if the message generated by AI like a human-message and match the conversation.Modify the message if not.
      
       Chat History:`+history+`
       Human B(generated by AI):{chat}
       Revised Result:`;
    const checkPromptTemplate = new PromptTemplate({
      inputVariables: ["chat"],
      template: checkTemplate,
    });
    const checkChain = new LLMChain({
      llm: checkLLM,
      prompt: checkPromptTemplate,
      outputKey: "checkedChat",
    });
    
    const overallChain = new SequentialChain({
      chains: [chatChain, checkChain],
      inputVariables: ["history", "input"],
      // Here we return multiple variables
      outputVariables: ["chat", "checkedChat"],
      verbose: true,
    });
    const chainExecutionResult = await overallChain.call({
      history: history,
      input: value,
    });
    setAiChain(overallChain);
    console.log(chainExecutionResult);
  }
//==========================================================================================

  const getMessages = async () =>{
      if(userInput && userName && otheruserName){  //------------------------------------------------------if user has name
        if(!currentTitle){
          setCurrentTitle(value);
        }
        setPreviousChats(previousChats => ([...previousChats, 
        {
          title: currentTitle?currentTitle:value,
          role: userName,
          content: value,
        }]));
        setHistory(history+'A:'+value);
        setUserInput(history);
      
        // getAImessages();
      if(!initialized){
        firstAImessage();
      }else{
        const chainExecutionResult = await aiChain.call({
          history: history,
          input: value,
        });
        console.log(chainExecutionResult);
      }
      
    //==========================================================================================
      if(value == '結束'){
        console.log('555');
        socket.emit('messageSocket', value);  //-------------------------------------------------------send progress to server
      }
    //==========================================================================================
    }else if(!userName && userInput){
      setUserName(value);
      console.log('userName set : '+value);
      setUserInput("");
    }else if(!otheruserName && userInput){
      setOtheruserName(value);
      console.log('otheruserName set : '+value);
      setUserInput("");
      socket.emit('messageSocket', value);
    }
  }

//==========================================================================================

  const getAImessages = async () =>{
    const llm = new OpenAI({ openAIApiKey:API_KEY, temperature:0.9 });
    const template = `he following is the chat history between two friendly humans, A and B. You are going to mimic human B and create a response for him/her.
    
    Chat History: {history}
    Human A: {input}
    Human B:
    `
    const prompt_template = new PromptTemplate({inputVariables:["history", "input"], template:template});
    const location_chain = new LLMChain({llm:llm, prompt:prompt_template});

    // meal 链
    const template1 = `The following is the chat history between two friendly humans, A and B. An AI generated a message for human B to respond to human A, you are going to check if the message generated by AI like a human-message and match the conversation.Modify the message if not.
      
    Chat History:{history}
    Human B(generated by AI):{chat}
    Revised Result:
    `
    const prompt_template1 = new PromptTemplate({inputVariables:["history", "chat"], template:template1});
    const meal_chain = new LLMChain({llm:llm, prompt:prompt_template1});

    // 通过 SimpleSequentialChain 串联起来，第一个答案会被替换第二个中的user_meal，然后再进行询问
    const overall_chain = new SimpleSequentialChain({chains:[location_chain, meal_chain], verbose:true});
    const review = await overall_chain.run(history,value);
    console.log(review);
  }
  // const options = {
    //   method: 'POST',
    //     headers: {
    //         "Access-Control-Allow-Origin": '*',
    //         "Content-Type": "application/json",
    //         "Authorization": "Bearer " + API_KEY
    //     },
    //     body: JSON.stringify({
    //         "model": "gpt-3.5-turbo",
    //         "messages": [{ "role": "user", "content": value }]  //----------------------------send message to openai
    //     })
    // }
    // try{
    //   // const response = await fetch('https://api.openai.com/v1/chat/completions', options);
    //   const response = await fetch('https://api.openai.com/v1/chat/completions', options);
    //   const data = await response.json();
    //   console.log(data);
    //   setMessage(data.choices[0].message);   //-------------------------------------------------------log ai response & set as message
      
    // } catch (error){
    //   console.error(error);
    // }
//==========================================================================================

  const createNewChat = () => {
    setCurrentTitle(null);
    setValue("");
    setUserInput("");
    setMessage(null);
    setUserName(null);
    // setInitialized(null);
  }

//==========================================================================================

  useEffect(() => {
    console.log(currentTitle, value, message);
    if(!userName && value && message){
      setUserName(value);
      setUserInput("");
    }
    
    if(!currentTitle && value && message && userName){
      setCurrentTitle(value);
    }
    if(currentTitle && message && otheruserName){ //-----------------------------------------------------assign user input(value) and ai message
      setPreviousChats(previousChats => ([...previousChats, 
      {
        title: currentTitle,
        role: otheruserName,
        content: message.content,
      }]));
    }
    

//==========================================================================================

    socket.on('messageSocket', (messageSocket) => {
      if(messageSocket.sender != socket.id){
          if(!otheruserName){
            setOtheruserName(messageSocket.content);
            alert('🫰 另一位參與者 : '+messageSocket.content+' 已加入！ 🫰');
            if(messageSocket.content == '結束'){
              console.log('9999');
            }
          }
      }
    });

//==========================================================================================

  }, [message, currentTitle, messageSocket]);

  console.log(previousChats);
  // console.log("Other user name : " + otheruserName);
  const currentChat = previousChats.filter(previousChats => previousChats.title === currentTitle); //--------------------set currentchat(now showing chat) from previouschats
  // setValue("");
  // const uniquTitles = Array.from( new Set(previousChats.map(previousChat => previousChat.title)));
  // console.log(uniquTitles);
//==========================================================================================

  return (
    
    <div className="app">
        <section className = "main"> 
            {!currentTitle && <h1> Turing's Chatroom</h1>}
            <ul className="feed">
              
              {currentChat?.map((chatMessage, index) => <li key={index} className={chatMessage.role === userName ? 'li1' : 'li2'}>
                <p className={chatMessage.role === userName ? 'role' : 'role1'}>{chatMessage.role}</p>
                <p className={chatMessage.role === userName ? 'content' : 'content1'}>{chatMessage.content}</p>   {/* distinguish message owner  */}
                
              </li>)}
            </ul>
            <div className="bottom-section">
                <div className="input-container">
                    {/* <button onClick={createNewChat}>👋</button> */}
                    <input value={userInput} onChange={(e) => {
                        setUserInput(e.target.value);
                        setValue(e.target.value);
                      }
                    }/>
                    <div id="submit" onClick={getMessages}>🫰</div>
                    
                </div>
            </div>
      </section>
    </div>

  );
}

export default Fp;

  // const turnpages = async () =>{
  //   try{
  //     if(value == '結束'){
  //       console.log('88888888')
  //       // a = 1
  //     }else{
  //       a = 2
  //     }
  //   } catch (error){
  //     console.error(error);
  //   }
  // }